AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Cloud Resume backend Lambda

Resources:
  VisitorCounterFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: visitor-counter
      Runtime: python3.11
      Handler: app.lambda_handler
      CodeUri: .
      MemorySize: 128
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: VisitorCountTable
      Environment:
        Variables:
          TABLE_NAME: VisitorCountTable

  VisitorCountTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: VisitorCountTable
      PrimaryKey:
        Name: id
        Type: String

Outputs:
  VisitorCounterFunction:
    Description: Lambda Function ARN
    Value: !GetAtt VisitorCounterFunction.Arn
